
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'npx tsx ./prisma/seed.ts',
  },
  datasource: {
    url: String(process.env.DATABASE_URL),
  },
});
// import { defineConfig } from '@prisma/config';

// export default defineConfig({
//   datasource: {
//     url: process.env.DATABASE_URL,
//   },
// });